bin/netcp: src/netcp.h src/netcp.c toolchain
	@mkdir -p bin
	toolchain/bin/arm-linux-androideabi-gcc \
		--sysroot=toolchain/sysroot \
	  src/netcp.c \
		-o bin/netcp \
		-Wall

clean:
	@rm bin/netcp
	@rm -r bin

toolchain:
	# TODO: Err if ANDROID_NDK not set.
	${ANDROID_NDK}/build/tools/make-standalone-toolchain.sh \
		--platform=android-18 \
		--toolchain=arm-linux-androideabi-4.8 \
		--install-dir=${PWD}/toolchain
